services:
  database:
    container_name: "postgres-dev"
    image: "postgres:16-alpine3.19"
    env_file:
      - ../.env.development
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-h", "localhost"]
      start_period: 1s
      interval: 1s
      timeout: 1s
      retries: 120 # 2 minutes
